/* Auto-generated by genmsg_cpp for file /home/duwenwen/Workspace/pointcloudcompress/ros-message-transport/udpmulti_transport/msg/UDPMultTopic.msg */
#ifndef UDPMULTI_TRANSPORT_MESSAGE_UDPMULTTOPIC_H
#define UDPMULTI_TRANSPORT_MESSAGE_UDPMULTTOPIC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace udpmulti_transport
{
template <class ContainerAllocator>
struct UDPMultTopic_ {
  typedef UDPMultTopic_<ContainerAllocator> Type;

  UDPMultTopic_()
  : topic()
  , port(0)
  {
  }

  UDPMultTopic_(const ContainerAllocator& _alloc)
  : topic(_alloc)
  , port(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  topic;

  typedef uint16_t _port_type;
  uint16_t port;


  typedef boost::shared_ptr< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator>  const> ConstPtr;
}; // struct UDPMultTopic
typedef  ::udpmulti_transport::UDPMultTopic_<std::allocator<void> > UDPMultTopic;

typedef boost::shared_ptr< ::udpmulti_transport::UDPMultTopic> UDPMultTopicPtr;
typedef boost::shared_ptr< ::udpmulti_transport::UDPMultTopic const> UDPMultTopicConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace udpmulti_transport

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> > {
  static const char* value() 
  {
    return "48c2b64a5f7c125c67479f2fc43203a5";
  }

  static const char* value(const  ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x48c2b64a5f7c125cULL;
  static const uint64_t static_value2 = 0x67479f2fc43203a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> > {
  static const char* value() 
  {
    return "udpmulti_transport/UDPMultTopic";
  }

  static const char* value(const  ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string topic\n\
uint16 port\n\
\n\
";
  }

  static const char* value(const  ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.topic);
    stream.next(m.port);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct UDPMultTopic_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::udpmulti_transport::UDPMultTopic_<ContainerAllocator> & v) 
  {
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
    s << indent << "port: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.port);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UDPMULTI_TRANSPORT_MESSAGE_UDPMULTTOPIC_H

