/* Auto-generated by genmsg_cpp for file /home/duwenwen/Workspace/pointcloudcompress/ros-message-transport/sharedmem_transport/srv/SHMReleaseMemory.srv */
#ifndef SHAREDMEM_TRANSPORT_SERVICE_SHMRELEASEMEMORY_H
#define SHAREDMEM_TRANSPORT_SERVICE_SHMRELEASEMEMORY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace sharedmem_transport
{
template <class ContainerAllocator>
struct SHMReleaseMemoryRequest_ {
  typedef SHMReleaseMemoryRequest_<ContainerAllocator> Type;

  SHMReleaseMemoryRequest_()
  : topic()
  {
  }

  SHMReleaseMemoryRequest_(const ContainerAllocator& _alloc)
  : topic(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  topic;


  typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct SHMReleaseMemoryRequest
typedef  ::sharedmem_transport::SHMReleaseMemoryRequest_<std::allocator<void> > SHMReleaseMemoryRequest;

typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryRequest> SHMReleaseMemoryRequestPtr;
typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryRequest const> SHMReleaseMemoryRequestConstPtr;



template <class ContainerAllocator>
struct SHMReleaseMemoryResponse_ {
  typedef SHMReleaseMemoryResponse_<ContainerAllocator> Type;

  SHMReleaseMemoryResponse_()
  : result(0)
  {
  }

  SHMReleaseMemoryResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct SHMReleaseMemoryResponse
typedef  ::sharedmem_transport::SHMReleaseMemoryResponse_<std::allocator<void> > SHMReleaseMemoryResponse;

typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryResponse> SHMReleaseMemoryResponsePtr;
typedef boost::shared_ptr< ::sharedmem_transport::SHMReleaseMemoryResponse const> SHMReleaseMemoryResponseConstPtr;


struct SHMReleaseMemory
{

typedef SHMReleaseMemoryRequest Request;
typedef SHMReleaseMemoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SHMReleaseMemory
} // namespace sharedmem_transport

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d8f94bae31b356b24d0427f80426d0c3";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd8f94bae31b356b2ULL;
  static const uint64_t static_value2 = 0x4d0427f80426d0c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sharedmem_transport/SHMReleaseMemoryRequest";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string topic\n\
\n\
";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sharedmem_transport/SHMReleaseMemoryResponse";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.topic);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct SHMReleaseMemoryRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct SHMReleaseMemoryResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<sharedmem_transport::SHMReleaseMemory> {
  static const char* value() 
  {
    return "9014a4b52c1ba99c200758d58f7a1006";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemory&) { return value(); } 
};

template<>
struct DataType<sharedmem_transport::SHMReleaseMemory> {
  static const char* value() 
  {
    return "sharedmem_transport/SHMReleaseMemory";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemory&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9014a4b52c1ba99c200758d58f7a1006";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sharedmem_transport/SHMReleaseMemory";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemoryRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9014a4b52c1ba99c200758d58f7a1006";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "sharedmem_transport/SHMReleaseMemory";
  }

  static const char* value(const sharedmem_transport::SHMReleaseMemoryResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // SHAREDMEM_TRANSPORT_SERVICE_SHMRELEASEMEMORY_H

