(cl:defpackage sharedmem_transport-srv
  (:use )
  (:export
   "SHMGETBLOCKS"
   "<SHMGETBLOCKS-REQUEST>"
   "SHMGETBLOCKS-REQUEST"
   "<SHMGETBLOCKS-RESPONSE>"
   "SHMGETBLOCKS-RESPONSE"
   "SHMCLEARALL"
   "<SHMCLEARALL-REQUEST>"
   "SHMCLEARALL-REQUEST"
   "<SHMCLEARALL-RESPONSE>"
   "SHMCLEARALL-RESPONSE"
   "SHMRELEASEMEMORY"
   "<SHMRELEASEMEMORY-REQUEST>"
   "SHMRELEASEMEMORY-REQUEST"
   "<SHMRELEASEMEMORY-RESPONSE>"
   "SHMRELEASEMEMORY-RESPONSE"
  ))

