(cl:defpackage throttled_transport-srv
  (:use )
  (:export
   "SETTHROTTLINGPARAMETERS"
   "<SETTHROTTLINGPARAMETERS-REQUEST>"
   "SETTHROTTLINGPARAMETERS-REQUEST"
   "<SETTHROTTLINGPARAMETERS-RESPONSE>"
   "SETTHROTTLINGPARAMETERS-RESPONSE"
  ))

